// Auto-generated data file. Includes change disclaimers from the
// most recent update run. Disclaimers older than 30 days are hidden
// client-side (see changeBadgeHtml in carforyou.html).
const CARFORYOU_DATA = [
  {
    "maerke": "Volkswagen",
    "model": "T-Roc",
    "variant": "R-Line 1.5 eTSI Mild hybrid DSG7 150 hk",
    "udbetaling_kr": 0,
    "ydelse_kr": 3995,
    "loebetid_mdr": 12,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Volkswagen",
    "model": "T-Roc",
    "variant": "R-Line 1.5 eTSI Mild hybrid DSG7 150 hk",
    "udbetaling_kr": 5000,
    "ydelse_kr": 3495,
    "loebetid_mdr": 12,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Buzz Kort",
    "variant": "Life 286 hk",
    "udbetaling_kr": 30000,
    "ydelse_kr": 4395,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Buzz Kort",
    "variant": "Life 286 hk",
    "udbetaling_kr": 50000,
    "ydelse_kr": 3795,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Buzz Kort",
    "variant": "Style 286 hk",
    "udbetaling_kr": 30000,
    "ydelse_kr": 5595,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Buzz Kort",
    "variant": "Style 286 hk",
    "udbetaling_kr": 50000,
    "ydelse_kr": 4995,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Buzz Kort",
    "variant": "Life 4MOTION 340 hk *",
    "udbetaling_kr": 50000,
    "ydelse_kr": 4195,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Buzz Kort",
    "variant": "Style 4MOTION 340 hk *",
    "udbetaling_kr": 50000,
    "ydelse_kr": 5395,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Buzz Kort",
    "variant": "GTX 4MOTION 340 hk *",
    "udbetaling_kr": 50000,
    "ydelse_kr": 5995,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Buzz Lang",
    "variant": "Life 286 hk",
    "udbetaling_kr": 30000,
    "ydelse_kr": 4795,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Buzz Lang",
    "variant": "Life 286 hk",
    "udbetaling_kr": 50000,
    "ydelse_kr": 4195,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Buzz Lang",
    "variant": "Style 286 hk",
    "udbetaling_kr": 30000,
    "ydelse_kr": 5995,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Buzz Lang",
    "variant": "Style 286 hk",
    "udbetaling_kr": 50000,
    "ydelse_kr": 5395,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Buzz Lang",
    "variant": "Life 4MOTION 340 hk *",
    "udbetaling_kr": 50000,
    "ydelse_kr": 4595,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Buzz Lang",
    "variant": "Style 4MOTION 340 hk *",
    "udbetaling_kr": 50000,
    "ydelse_kr": 5795,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Buzz Lang",
    "variant": "GTX 4MOTION 340 hk *",
    "udbetaling_kr": 50000,
    "ydelse_kr": 6495,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Polo",
    "variant": "Life Launch Edition 211 hk",
    "udbetaling_kr": 25000,
    "ydelse_kr": 2695,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Polo",
    "variant": "Style Launch Edition 211 hk",
    "udbetaling_kr": 15000,
    "ydelse_kr": 3295,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Polo",
    "variant": "Life Launch Edition 211 hk",
    "udbetaling_kr": 10000,
    "ydelse_kr": 3095,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Polo",
    "variant": "Style Launch Edition 211 hk",
    "udbetaling_kr": 5000,
    "ydelse_kr": 3795,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.3 Neo",
    "variant": "Trend 170 hk",
    "udbetaling_kr": 30000,
    "ydelse_kr": 2295,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.3 Neo",
    "variant": "Life 190 hk",
    "udbetaling_kr": 30000,
    "ydelse_kr": 2595,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.3 Neo",
    "variant": "Life 231 hk",
    "udbetaling_kr": 30000,
    "ydelse_kr": 2995,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.3 Neo",
    "variant": "Style 190 hk",
    "udbetaling_kr": 30000,
    "ydelse_kr": 2995,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.3 Neo",
    "variant": "Style 231 hk",
    "udbetaling_kr": 30000,
    "ydelse_kr": 3395,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.3 Neo",
    "variant": "Trend 170 hk",
    "udbetaling_kr": 15000,
    "ydelse_kr": 2495,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback",
    "change": {
      "types": [
        "price_down"
      ],
      "notes": [
        "Månedlig ydelse ændret fra 2.695 kr. til 2.495 kr. (-200 kr.)."
      ],
      "date": "2026-08-09"
    }
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.3 Neo",
    "variant": "Life 190 hk",
    "udbetaling_kr": 15000,
    "ydelse_kr": 2995,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.3 Neo",
    "variant": "Life 231 hk",
    "udbetaling_kr": 15000,
    "ydelse_kr": 3395,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.3 Neo",
    "variant": "Style 190 hk",
    "udbetaling_kr": 15000,
    "ydelse_kr": 3395,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.3 Neo",
    "variant": "Style 231 hk",
    "udbetaling_kr": 15000,
    "ydelse_kr": 3795,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.3 Neo",
    "variant": "Life 170 hk",
    "udbetaling_kr": 30000,
    "ydelse_kr": 2495,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.3 Neo",
    "variant": "Life 170 hk",
    "udbetaling_kr": 15000,
    "ydelse_kr": 2895,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.4",
    "variant": "Move 286 hk",
    "udbetaling_kr": 20000,
    "ydelse_kr": 4295,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv",
    "change": {
      "types": [
        "price_up"
      ],
      "notes": [
        "Månedlig ydelse ændret fra 3.995 kr. til 4.295 kr. (+300 kr.)."
      ],
      "date": "2026-08-09"
    }
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.4",
    "variant": "Move 286 hk",
    "udbetaling_kr": 45000,
    "ydelse_kr": 3295,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.4",
    "variant": "Style 286 hk",
    "udbetaling_kr": 20000,
    "ydelse_kr": 4295,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.4",
    "variant": "Style 286 hk",
    "udbetaling_kr": 45000,
    "ydelse_kr": 3595,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.4",
    "variant": "Style Edition 286 hk",
    "udbetaling_kr": 20000,
    "ydelse_kr": 4595,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.4",
    "variant": "Style Edition 286 hk",
    "udbetaling_kr": 45000,
    "ydelse_kr": 3895,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.4",
    "variant": "GTX Max Edition 340 hk * 4MOTION",
    "udbetaling_kr": 45000,
    "ydelse_kr": 4795,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.7 Tourer",
    "variant": "Style S 286 hk",
    "udbetaling_kr": 30000,
    "ydelse_kr": 4995,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.7 Tourer",
    "variant": "Style S 286 hk",
    "udbetaling_kr": 60000,
    "ydelse_kr": 4195,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.7 Tourer",
    "variant": "GTX Max 340 hk * 4MOTION",
    "udbetaling_kr": 60000,
    "ydelse_kr": 6595,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.5",
    "variant": "Style 286 hk",
    "udbetaling_kr": 20000,
    "ydelse_kr": 4295,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.5",
    "variant": "Style 286 hk",
    "udbetaling_kr": 45000,
    "ydelse_kr": 3595,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.5",
    "variant": "Style Edition 286 hk",
    "udbetaling_kr": 20000,
    "ydelse_kr": 4595,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.5",
    "variant": "Style Edition 286 hk",
    "udbetaling_kr": 45000,
    "ydelse_kr": 3895,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Kia",
    "model": "PV5 Passenger",
    "variant": "Prestige",
    "udbetaling_kr": 14995,
    "ydelse_kr": 3695,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://kiaonline.dk/biler/pv5-passenger/",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Kia",
    "model": "PV5 Passenger",
    "variant": "Prestige",
    "udbetaling_kr": 29995,
    "ydelse_kr": 3095,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://kiaonline.dk/biler/pv5-passenger/",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Kia",
    "model": "PV5 Passenger",
    "variant": "Upgrade",
    "udbetaling_kr": 14995,
    "ydelse_kr": 3895,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://kiaonline.dk/biler/pv5-passenger/",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Kia",
    "model": "PV5 Passenger",
    "variant": "Upgrade",
    "udbetaling_kr": 29995,
    "ydelse_kr": 3295,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://kiaonline.dk/biler/pv5-passenger/",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Kia",
    "model": "EV4",
    "variant": "Prestige",
    "udbetaling_kr": 19995,
    "ydelse_kr": 3695,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://kiaonline.dk/biler/ev4/",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Kia",
    "model": "EV4",
    "variant": "Prestige",
    "udbetaling_kr": 49995,
    "ydelse_kr": 2495,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://kiaonline.dk/biler/ev4/",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Kia",
    "model": "EV4",
    "variant": "Upgrade",
    "udbetaling_kr": 19995,
    "ydelse_kr": 3995,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://kiaonline.dk/biler/ev4/",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Kia",
    "model": "EV4",
    "variant": "Upgrade",
    "udbetaling_kr": 49995,
    "ydelse_kr": 2995,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://kiaonline.dk/biler/ev4/",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Kia",
    "model": "EV5",
    "variant": "Prestige",
    "udbetaling_kr": 29995,
    "ydelse_kr": 3995,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.kia.com/dk/modeller/ev5/oplev/",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Toyota",
    "model": "Yaris",
    "variant": "Yaris Hybrid Active 1.5 116 HK",
    "udbetaling_kr": 9999,
    "ydelse_kr": 3599,
    "loebetid_mdr": 36,
    "km_aar": 15000,
    "kilde_url": "https://www.toyota.dk/kampagner/yaris-active-pl-jan26-ID-22-2026",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback",
    "change": {
      "types": [
        "down_up"
      ],
      "notes": [
        "Udbetaling (engangsgebyr) ændret fra 4.999 kr. til 9.999 kr. (+5.000 kr.)."
      ],
      "date": "2026-08-09"
    }
  },
  {
    "maerke": "Toyota",
    "model": "C-HR+",
    "variant": "Active 165 kW (224 hk)",
    "udbetaling_kr": 9999,
    "ydelse_kr": 3999,
    "loebetid_mdr": 36,
    "km_aar": 15000,
    "kilde_url": "https://www.toyota.dk/privatleasing",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Toyota",
    "model": "C-HR+",
    "variant": "Active 252 kW (343 hk)",
    "udbetaling_kr": 9999,
    "ydelse_kr": 4299,
    "loebetid_mdr": 36,
    "km_aar": 15000,
    "kilde_url": "https://www.toyota.dk/privatleasing",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Toyota",
    "model": "bZ4X",
    "variant": "Active Tech 165 kW (224 hk)",
    "udbetaling_kr": 9999,
    "ydelse_kr": 4499,
    "loebetid_mdr": 36,
    "km_aar": 15000,
    "kilde_url": "https://www.toyota.dk/privatleasing",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Toyota",
    "model": "bZ4X",
    "variant": "Active Tech 252 kW (343 hk)",
    "udbetaling_kr": 9999,
    "ydelse_kr": 4799,
    "loebetid_mdr": 36,
    "km_aar": 15000,
    "kilde_url": "https://www.toyota.dk/privatleasing",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Toyota",
    "model": "bZ4X Touring",
    "variant": "Active Tech 165 kW (224 hk)",
    "udbetaling_kr": 9999,
    "ydelse_kr": 4999,
    "loebetid_mdr": 36,
    "km_aar": 15000,
    "kilde_url": "https://www.toyota.dk/privatleasing",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Toyota",
    "model": "bZ4X Touring",
    "variant": "Active Tech 280 kW (380 hk)",
    "udbetaling_kr": 9999,
    "ydelse_kr": 5499,
    "loebetid_mdr": 36,
    "km_aar": 15000,
    "kilde_url": "https://www.toyota.dk/privatleasing",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Renault",
    "model": "4",
    "variant": "Evolution EV40",
    "udbetaling_kr": 14995,
    "ydelse_kr": 2695,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://www.renault.dk/kob/privatleasing/renault-4-e-tech-electric",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Renault",
    "model": "5",
    "variant": "Evolution EV40",
    "udbetaling_kr": 14995,
    "ydelse_kr": 2395,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://www.renault.dk/kob/privatleasing/renault-5-e-tech-electric",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Renault",
    "model": "Scenic",
    "variant": "Techno 60 kWh",
    "udbetaling_kr": 19995,
    "ydelse_kr": 3195,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://www.renault.dk/kob/privatleasing/scenic-e-tech-electric",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Renault",
    "model": "Twingo",
    "variant": "Techno",
    "udbetaling_kr": 14995,
    "ydelse_kr": 2195,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://www.renault.dk/kob/privatleasing/twingo-e-tech-electric",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback",
    "change": {
      "types": [
        "price_down"
      ],
      "notes": [
        "Månedlig ydelse ændret fra 2.395 kr. til 2.195 kr. (-200 kr.)."
      ],
      "date": "2026-06-25"
    }
  },
  {
    "maerke": "Kia",
    "model": "EV5",
    "variant": "Prestige",
    "udbetaling_kr": 29995,
    "ydelse_kr": 3995,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://kiaonline.dk/biler/ev5/",
    "sidst_tjekket": "2026-08-04",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Renault",
    "model": "4",
    "variant": "Techno EV52",
    "udbetaling_kr": 14995,
    "ydelse_kr": 2995,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://edge.sitecorecloud.io/hedinitaban27a1-hedin8837-prod5c4b-4604/media/project/hedin/distribution-cars/renaultdksite/cardocuments/privatleasing-renault.pdf",
    "sidst_tjekket": "2026-08-04",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Renault",
    "model": "5",
    "variant": "Techno EV52",
    "udbetaling_kr": 14995,
    "ydelse_kr": 2795,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://edge.sitecorecloud.io/hedinitaban27a1-hedin8837-prod5c4b-4604/media/project/hedin/distribution-cars/renaultdksite/cardocuments/privatleasing-renault.pdf",
    "sidst_tjekket": "2026-08-04",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Renault",
    "model": "Scenic",
    "variant": "Techno 60 kWh",
    "udbetaling_kr": 39995,
    "ydelse_kr": 2595,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://edge.sitecorecloud.io/hedinitaban27a1-hedin8837-prod5c4b-4604/media/project/hedin/distribution-cars/renaultdksite/cardocuments/privatleasing-renault.pdf",
    "sidst_tjekket": "2026-08-04",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Renault",
    "model": "Scenic",
    "variant": "Techno 87 kWh",
    "udbetaling_kr": 39995,
    "ydelse_kr": 3195,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://edge.sitecorecloud.io/hedinitaban27a1-hedin8837-prod5c4b-4604/media/project/hedin/distribution-cars/renaultdksite/cardocuments/privatleasing-renault.pdf",
    "sidst_tjekket": "2026-08-04",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Renault",
    "model": "Scenic",
    "variant": "Esprit Alpine 87 kWh",
    "udbetaling_kr": 39995,
    "ydelse_kr": 3395,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://edge.sitecorecloud.io/hedinitaban27a1-hedin8837-prod5c4b-4604/media/project/hedin/distribution-cars/renaultdksite/cardocuments/privatleasing-renault.pdf",
    "sidst_tjekket": "2026-08-04",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Renault",
    "model": "Scenic",
    "variant": "Iconic 87 kWh",
    "udbetaling_kr": 39995,
    "ydelse_kr": 3595,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://edge.sitecorecloud.io/hedinitaban27a1-hedin8837-prod5c4b-4604/media/project/hedin/distribution-cars/renaultdksite/cardocuments/privatleasing-renault.pdf",
    "sidst_tjekket": "2026-08-04",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Renault",
    "model": "Scenic",
    "variant": "Techno 87 kWh (lav udbetaling)",
    "udbetaling_kr": 19995,
    "ydelse_kr": 3895,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://edge.sitecorecloud.io/hedinitaban27a1-hedin8837-prod5c4b-4604/media/project/hedin/distribution-cars/renaultdksite/cardocuments/privatleasing-renault.pdf",
    "sidst_tjekket": "2026-08-04",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Renault",
    "model": "Scenic",
    "variant": "Esprit Alpine 87 kWh (lav udbetaling)",
    "udbetaling_kr": 19995,
    "ydelse_kr": 4095,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://edge.sitecorecloud.io/hedinitaban27a1-hedin8837-prod5c4b-4604/media/project/hedin/distribution-cars/renaultdksite/cardocuments/privatleasing-renault.pdf",
    "sidst_tjekket": "2026-08-04",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Renault",
    "model": "Scenic",
    "variant": "Iconic 87 kWh (lav udbetaling)",
    "udbetaling_kr": 19995,
    "ydelse_kr": 4295,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://edge.sitecorecloud.io/hedinitaban27a1-hedin8837-prod5c4b-4604/media/project/hedin/distribution-cars/renaultdksite/cardocuments/privatleasing-renault.pdf",
    "sidst_tjekket": "2026-08-04",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Kia",
    "model": "EV3",
    "variant": "Air",
    "udbetaling_kr": 19995,
    "ydelse_kr": 2795,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://kiaonline.dk/biler/ev3/",
    "sidst_tjekket": "2026-08-09",
    "status": "Aktiv",
    "type": "suv",
    "change": {
      "types": [
        "new"
      ],
      "notes": [
        "Ny model/variant tilføjet siden sidste opdatering."
      ],
      "date": "2026-08-09"
    }
  }
];
