const CARFORYOU_DATA = [
  {
    "maerke": "Volkswagen",
    "model": "T-Roc",
    "variant": "R-Line 1.5 eTSI Mild hybrid DSG7 150 hk",
    "udbetaling_kr": 0,
    "ydelse_kr": 3995,
    "loebetid_mdr": 12,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Volkswagen",
    "model": "T-Roc",
    "variant": "R-Line 1.5 eTSI Mild hybrid DSG7 150 hk",
    "udbetaling_kr": 5000,
    "ydelse_kr": 3495,
    "loebetid_mdr": 12,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Buzz Kort",
    "variant": "Life 286 hk",
    "udbetaling_kr": 30000,
    "ydelse_kr": 4395,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Buzz Kort",
    "variant": "Life 286 hk",
    "udbetaling_kr": 50000,
    "ydelse_kr": 3795,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Buzz Kort",
    "variant": "Style 286 hk",
    "udbetaling_kr": 30000,
    "ydelse_kr": 5595,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Buzz Kort",
    "variant": "Style 286 hk",
    "udbetaling_kr": 50000,
    "ydelse_kr": 4995,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Buzz Kort",
    "variant": "Life 4MOTION 340 hk *",
    "udbetaling_kr": 50000,
    "ydelse_kr": 4195,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Buzz Kort",
    "variant": "Style 4MOTION 340 hk *",
    "udbetaling_kr": 50000,
    "ydelse_kr": 5395,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Buzz Kort",
    "variant": "GTX 4MOTION 340 hk *",
    "udbetaling_kr": 50000,
    "ydelse_kr": 5995,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Buzz Lang",
    "variant": "Life 286 hk",
    "udbetaling_kr": 30000,
    "ydelse_kr": 4795,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Buzz Lang",
    "variant": "Life 286 hk",
    "udbetaling_kr": 50000,
    "ydelse_kr": 4195,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Buzz Lang",
    "variant": "Style 286 hk",
    "udbetaling_kr": 30000,
    "ydelse_kr": 5995,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Buzz Lang",
    "variant": "Style 286 hk",
    "udbetaling_kr": 50000,
    "ydelse_kr": 5395,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Buzz Lang",
    "variant": "Life 4MOTION 340 hk *",
    "udbetaling_kr": 50000,
    "ydelse_kr": 4595,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Buzz Lang",
    "variant": "Style 4MOTION 340 hk *",
    "udbetaling_kr": 50000,
    "ydelse_kr": 5795,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Buzz Lang",
    "variant": "GTX 4MOTION 340 hk *",
    "udbetaling_kr": 50000,
    "ydelse_kr": 6495,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Polo",
    "variant": "Life Launch Edition 211 hk",
    "udbetaling_kr": 25000,
    "ydelse_kr": 2695,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Polo",
    "variant": "Style Launch Edition 211 hk",
    "udbetaling_kr": 15000,
    "ydelse_kr": 3295,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Polo",
    "variant": "Life Launch Edition 211 hk",
    "udbetaling_kr": 10000,
    "ydelse_kr": 3095,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID. Polo",
    "variant": "Style Launch Edition 211 hk",
    "udbetaling_kr": 5000,
    "ydelse_kr": 3795,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.3 Neo",
    "variant": "Trend 170 hk",
    "udbetaling_kr": 30000,
    "ydelse_kr": 2295,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.3 Neo",
    "variant": "Life 190 hk",
    "udbetaling_kr": 30000,
    "ydelse_kr": 2595,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.3 Neo",
    "variant": "Life 231 hk",
    "udbetaling_kr": 30000,
    "ydelse_kr": 2995,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.3 Neo",
    "variant": "Style 190 hk",
    "udbetaling_kr": 30000,
    "ydelse_kr": 2995,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.3 Neo",
    "variant": "Style 231 hk",
    "udbetaling_kr": 30000,
    "ydelse_kr": 3395,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.3 Neo",
    "variant": "Trend 170 hk",
    "udbetaling_kr": 15000,
    "ydelse_kr": 2495,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback",
    "change": {
      "types": [
        "price_down"
      ],
      "notes": [
        "Månedlig ydelse ændret fra 2.695 kr. til 2.495 kr. (-200 kr.)."
      ],
      "date": "2026-08-09"
    }
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.3 Neo",
    "variant": "Life 190 hk",
    "udbetaling_kr": 15000,
    "ydelse_kr": 2995,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.3 Neo",
    "variant": "Life 231 hk",
    "udbetaling_kr": 15000,
    "ydelse_kr": 3395,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.3 Neo",
    "variant": "Style 190 hk",
    "udbetaling_kr": 15000,
    "ydelse_kr": 3395,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.3 Neo",
    "variant": "Style 231 hk",
    "udbetaling_kr": 15000,
    "ydelse_kr": 3795,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.3 Neo",
    "variant": "Life 170 hk",
    "udbetaling_kr": 30000,
    "ydelse_kr": 2495,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.3 Neo",
    "variant": "Life 170 hk",
    "udbetaling_kr": 15000,
    "ydelse_kr": 2895,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.4",
    "variant": "Move 286 hk",
    "udbetaling_kr": 20000,
    "ydelse_kr": 4295,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv",
    "change": {
      "types": [
        "price_up"
      ],
      "notes": [
        "Månedlig ydelse ændret fra 3.995 kr. til 4.295 kr. (+300 kr.)."
      ],
      "date": "2026-08-09"
    }
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.4",
    "variant": "Move 286 hk",
    "udbetaling_kr": 45000,
    "ydelse_kr": 3295,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.4",
    "variant": "Style 286 hk",
    "udbetaling_kr": 20000,
    "ydelse_kr": 4295,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.4",
    "variant": "Style 286 hk",
    "udbetaling_kr": 45000,
    "ydelse_kr": 3595,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.4",
    "variant": "Style Edition 286 hk",
    "udbetaling_kr": 20000,
    "ydelse_kr": 4595,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.4",
    "variant": "Style Edition 286 hk",
    "udbetaling_kr": 45000,
    "ydelse_kr": 3895,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.4",
    "variant": "GTX Max Edition 340 hk * 4MOTION",
    "udbetaling_kr": 45000,
    "ydelse_kr": 4795,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.7 Tourer",
    "variant": "Style S 286 hk",
    "udbetaling_kr": 30000,
    "ydelse_kr": 4995,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.7 Tourer",
    "variant": "Style S 286 hk",
    "udbetaling_kr": 60000,
    "ydelse_kr": 4195,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.7 Tourer",
    "variant": "GTX Max 340 hk * 4MOTION",
    "udbetaling_kr": 60000,
    "ydelse_kr": 6595,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.5",
    "variant": "Style 286 hk",
    "udbetaling_kr": 20000,
    "ydelse_kr": 4295,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.5",
    "variant": "Style 286 hk",
    "udbetaling_kr": 45000,
    "ydelse_kr": 3595,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.5",
    "variant": "Style Edition 286 hk",
    "udbetaling_kr": 20000,
    "ydelse_kr": 4595,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Volkswagen",
    "model": "ID.5",
    "variant": "Style Edition 286 hk",
    "udbetaling_kr": 45000,
    "ydelse_kr": 3895,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://prislister.volkswagen.dk/leasingpriser",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Kia",
    "model": "PV5 Passenger",
    "variant": "Prestige",
    "udbetaling_kr": 14995,
    "ydelse_kr": 3695,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://kiaonline.dk/biler/pv5-passenger/",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Kia",
    "model": "PV5 Passenger",
    "variant": "Prestige",
    "udbetaling_kr": 29995,
    "ydelse_kr": 3095,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://kiaonline.dk/biler/pv5-passenger/",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Kia",
    "model": "PV5 Passenger",
    "variant": "Upgrade",
    "udbetaling_kr": 14995,
    "ydelse_kr": 3895,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://kiaonline.dk/biler/pv5-passenger/",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Kia",
    "model": "PV5 Passenger",
    "variant": "Upgrade",
    "udbetaling_kr": 29995,
    "ydelse_kr": 3295,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://kiaonline.dk/biler/pv5-passenger/",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "mpv"
  },
  {
    "maerke": "Kia",
    "model": "EV4",
    "variant": "Prestige",
    "udbetaling_kr": 19995,
    "ydelse_kr": 3695,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://kiaonline.dk/biler/ev4/",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Kia",
    "model": "EV4",
    "variant": "Prestige",
    "udbetaling_kr": 49995,
    "ydelse_kr": 2495,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://kiaonline.dk/biler/ev4/",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Kia",
    "model": "EV4",
    "variant": "Upgrade",
    "udbetaling_kr": 19995,
    "ydelse_kr": 3995,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://kiaonline.dk/biler/ev4/",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Kia",
    "model": "EV4",
    "variant": "Upgrade",
    "udbetaling_kr": 49995,
    "ydelse_kr": 2995,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://kiaonline.dk/biler/ev4/",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Kia",
    "model": "EV5",
    "variant": "Prestige",
    "udbetaling_kr": 29995,
    "ydelse_kr": 3995,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.kia.com/dk/modeller/ev5/oplev/",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Toyota",
    "model": "Yaris",
    "variant": "Yaris Hybrid Active 1.5 116 HK",
    "udbetaling_kr": 9999,
    "ydelse_kr": 3599,
    "loebetid_mdr": 36,
    "km_aar": 15000,
    "kilde_url": "https://www.toyota.dk/kampagner/yaris-active-pl-jan26-ID-22-2026",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback",
    "change": {
      "types": [
        "down_up"
      ],
      "notes": [
        "Udbetaling (engangsgebyr) ændret fra 4.999 kr. til 9.999 kr. (+5.000 kr.)."
      ],
      "date": "2026-08-09"
    }
  },
  {
    "maerke": "Toyota",
    "model": "C-HR+",
    "variant": "Active 165 kW (224 hk)",
    "udbetaling_kr": 9999,
    "ydelse_kr": 3999,
    "loebetid_mdr": 36,
    "km_aar": 15000,
    "kilde_url": "https://www.toyota.dk/privatleasing",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Toyota",
    "model": "C-HR+",
    "variant": "Active 252 kW (343 hk)",
    "udbetaling_kr": 9999,
    "ydelse_kr": 4299,
    "loebetid_mdr": 36,
    "km_aar": 15000,
    "kilde_url": "https://www.toyota.dk/privatleasing",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Toyota",
    "model": "bZ4X",
    "variant": "Active Tech 165 kW (224 hk)",
    "udbetaling_kr": 9999,
    "ydelse_kr": 4499,
    "loebetid_mdr": 36,
    "km_aar": 15000,
    "kilde_url": "https://www.toyota.dk/privatleasing",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Toyota",
    "model": "bZ4X",
    "variant": "Active Tech 252 kW (343 hk)",
    "udbetaling_kr": 9999,
    "ydelse_kr": 4799,
    "loebetid_mdr": 36,
    "km_aar": 15000,
    "kilde_url": "https://www.toyota.dk/privatleasing",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Toyota",
    "model": "bZ4X Touring",
    "variant": "Active Tech 165 kW (224 hk)",
    "udbetaling_kr": 9999,
    "ydelse_kr": 4999,
    "loebetid_mdr": 36,
    "km_aar": 15000,
    "kilde_url": "https://www.toyota.dk/privatleasing",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Toyota",
    "model": "bZ4X Touring",
    "variant": "Active Tech 280 kW (380 hk)",
    "udbetaling_kr": 9999,
    "ydelse_kr": 5499,
    "loebetid_mdr": 36,
    "km_aar": 15000,
    "kilde_url": "https://www.toyota.dk/privatleasing",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Renault",
    "model": "4",
    "variant": "Evolution EV40",
    "udbetaling_kr": 14995,
    "ydelse_kr": 2695,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://www.renault.dk/kob/privatleasing/renault-4-e-tech-electric",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Renault",
    "model": "5",
    "variant": "Evolution EV40",
    "udbetaling_kr": 14995,
    "ydelse_kr": 2395,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://www.renault.dk/kob/privatleasing/renault-5-e-tech-electric",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Renault",
    "model": "Scenic",
    "variant": "Techno 60 kWh",
    "udbetaling_kr": 19995,
    "ydelse_kr": 3195,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://www.renault.dk/kob/privatleasing/scenic-e-tech-electric",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Renault",
    "model": "Twingo",
    "variant": "Techno",
    "udbetaling_kr": 14995,
    "ydelse_kr": 2195,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://www.renault.dk/kob/privatleasing/twingo-e-tech-electric",
    "sidst_tjekket": "2026-08-08",
    "status": "Aktiv",
    "type": "hatchback",
    "change": {
      "types": [
        "price_down"
      ],
      "notes": [
        "Månedlig ydelse ændret fra 2.395 kr. til 2.195 kr. (-200 kr.)."
      ],
      "date": "2026-06-25"
    }
  },
  {
    "maerke": "Kia",
    "model": "EV5",
    "variant": "Prestige",
    "udbetaling_kr": 29995,
    "ydelse_kr": 3995,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://kiaonline.dk/biler/ev5/",
    "sidst_tjekket": "2026-08-04",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Renault",
    "model": "4",
    "variant": "Techno EV52",
    "udbetaling_kr": 14995,
    "ydelse_kr": 2995,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://edge.sitecorecloud.io/hedinitaban27a1-hedin8837-prod5c4b-4604/media/project/hedin/distribution-cars/renaultdksite/cardocuments/privatleasing-renault.pdf",
    "sidst_tjekket": "2026-08-04",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Renault",
    "model": "5",
    "variant": "Techno EV52",
    "udbetaling_kr": 14995,
    "ydelse_kr": 2795,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://edge.sitecorecloud.io/hedinitaban27a1-hedin8837-prod5c4b-4604/media/project/hedin/distribution-cars/renaultdksite/cardocuments/privatleasing-renault.pdf",
    "sidst_tjekket": "2026-08-04",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Renault",
    "model": "Scenic",
    "variant": "Techno 60 kWh",
    "udbetaling_kr": 39995,
    "ydelse_kr": 2595,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://edge.sitecorecloud.io/hedinitaban27a1-hedin8837-prod5c4b-4604/media/project/hedin/distribution-cars/renaultdksite/cardocuments/privatleasing-renault.pdf",
    "sidst_tjekket": "2026-08-04",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Renault",
    "model": "Scenic",
    "variant": "Techno 87 kWh",
    "udbetaling_kr": 39995,
    "ydelse_kr": 3195,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://edge.sitecorecloud.io/hedinitaban27a1-hedin8837-prod5c4b-4604/media/project/hedin/distribution-cars/renaultdksite/cardocuments/privatleasing-renault.pdf",
    "sidst_tjekket": "2026-08-04",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Renault",
    "model": "Scenic",
    "variant": "Esprit Alpine 87 kWh",
    "udbetaling_kr": 39995,
    "ydelse_kr": 3395,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://edge.sitecorecloud.io/hedinitaban27a1-hedin8837-prod5c4b-4604/media/project/hedin/distribution-cars/renaultdksite/cardocuments/privatleasing-renault.pdf",
    "sidst_tjekket": "2026-08-04",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Renault",
    "model": "Scenic",
    "variant": "Iconic 87 kWh",
    "udbetaling_kr": 39995,
    "ydelse_kr": 3595,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://edge.sitecorecloud.io/hedinitaban27a1-hedin8837-prod5c4b-4604/media/project/hedin/distribution-cars/renaultdksite/cardocuments/privatleasing-renault.pdf",
    "sidst_tjekket": "2026-08-04",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Renault",
    "model": "Scenic",
    "variant": "Techno 87 kWh (lav udbetaling)",
    "udbetaling_kr": 19995,
    "ydelse_kr": 3895,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://edge.sitecorecloud.io/hedinitaban27a1-hedin8837-prod5c4b-4604/media/project/hedin/distribution-cars/renaultdksite/cardocuments/privatleasing-renault.pdf",
    "sidst_tjekket": "2026-08-04",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Renault",
    "model": "Scenic",
    "variant": "Esprit Alpine 87 kWh (lav udbetaling)",
    "udbetaling_kr": 19995,
    "ydelse_kr": 4095,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://edge.sitecorecloud.io/hedinitaban27a1-hedin8837-prod5c4b-4604/media/project/hedin/distribution-cars/renaultdksite/cardocuments/privatleasing-renault.pdf",
    "sidst_tjekket": "2026-08-04",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Renault",
    "model": "Scenic",
    "variant": "Iconic 87 kWh (lav udbetaling)",
    "udbetaling_kr": 19995,
    "ydelse_kr": 4295,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://edge.sitecorecloud.io/hedinitaban27a1-hedin8837-prod5c4b-4604/media/project/hedin/distribution-cars/renaultdksite/cardocuments/privatleasing-renault.pdf",
    "sidst_tjekket": "2026-08-04",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Kia",
    "model": "EV3",
    "variant": "Air",
    "udbetaling_kr": 19995,
    "ydelse_kr": 2795,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://kiaonline.dk/biler/ev3/",
    "sidst_tjekket": "2026-08-09",
    "status": "Aktiv",
    "type": "suv",
    "change": {
      "types": [
        "new"
      ],
      "notes": [
        "Ny model/variant tilføjet siden sidste opdatering."
      ],
      "date": "2026-08-09"
    }
  },
  {
    "maerke": "Skoda",
    "model": "Kamiq",
    "variant": "Monte Carlo 1.0 TSI DSG7 115 hk",
    "udbetaling_kr": 9995,
    "ydelse_kr": 2995,
    "loebetid_mdr": 12,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/kamiq/kamiq",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Skoda",
    "model": "Kamiq",
    "variant": "Selection 1.0 TSI DSG7 115 hk",
    "udbetaling_kr": 14995,
    "ydelse_kr": 3695,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/kamiq/kamiq",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Skoda",
    "model": "Kamiq",
    "variant": "Monte Carlo 1.0 TSI DSG7 115 hk",
    "udbetaling_kr": 0,
    "ydelse_kr": 3995,
    "loebetid_mdr": 12,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/kamiq/kamiq",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Skoda",
    "model": "Scala",
    "variant": "Selection 1.0 TSI DSG7 115 hk",
    "udbetaling_kr": 14995,
    "ydelse_kr": 3595,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/scala/scala",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Skoda",
    "model": "Epiq",
    "variant": "55 Selection Intro Edition 211 hk",
    "udbetaling_kr": 9995,
    "ydelse_kr": 3595,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/epiq/epiq",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Skoda",
    "model": "Epiq",
    "variant": "55 Selection Intro Edition 211 hk",
    "udbetaling_kr": 24995,
    "ydelse_kr": 3195,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/epiq/epiq",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Skoda",
    "model": "Elroq",
    "variant": "60 Selection 190 hk",
    "udbetaling_kr": 14995,
    "ydelse_kr": 3395,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/elroq/elroq",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Skoda",
    "model": "Elroq",
    "variant": "60 Selection 190 hk",
    "udbetaling_kr": 34995,
    "ydelse_kr": 2895,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/elroq/elroq",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Skoda",
    "model": "Enyaq",
    "variant": "60 Selection 190 hk",
    "udbetaling_kr": 19995,
    "ydelse_kr": 3695,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/enyaq/ny-enyaq",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Skoda",
    "model": "Enyaq",
    "variant": "60 Selection 190 hk",
    "udbetaling_kr": 39995,
    "ydelse_kr": 2995,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/enyaq/ny-enyaq",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Skoda",
    "model": "Enyaq",
    "variant": "85 Selection 286 hk",
    "udbetaling_kr": 19995,
    "ydelse_kr": 3995,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/enyaq/ny-enyaq",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Skoda",
    "model": "Enyaq",
    "variant": "85 Selection 286 hk",
    "udbetaling_kr": 39995,
    "ydelse_kr": 3295,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/enyaq/ny-enyaq",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Skoda",
    "model": "Enyaq",
    "variant": "85 Sportline 286 hk",
    "udbetaling_kr": 19995,
    "ydelse_kr": 4595,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/enyaq/ny-enyaq",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Skoda",
    "model": "Enyaq",
    "variant": "85 Sportline 286 hk",
    "udbetaling_kr": 39995,
    "ydelse_kr": 3895,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/enyaq/ny-enyaq",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Skoda",
    "model": "Enyaq",
    "variant": "85x Selection 4x4 299 hk",
    "udbetaling_kr": 19995,
    "ydelse_kr": 4495,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/enyaq/ny-enyaq",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Skoda",
    "model": "Enyaq",
    "variant": "85x Selection 4x4 299 hk",
    "udbetaling_kr": 39995,
    "ydelse_kr": 3795,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/enyaq/ny-enyaq",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Skoda",
    "model": "Enyaq",
    "variant": "RS 4x4 340 hk",
    "udbetaling_kr": 39995,
    "ydelse_kr": 4495,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/enyaq/ny-enyaq",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Skoda",
    "model": "Enyaq Coupé",
    "variant": "85 Selection 286 hk",
    "udbetaling_kr": 19995,
    "ydelse_kr": 4595,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/enyaq/ny-enyaq-coupe",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Skoda",
    "model": "Enyaq Coupé",
    "variant": "85 Selection 286 hk",
    "udbetaling_kr": 39995,
    "ydelse_kr": 3895,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/enyaq/ny-enyaq-coupe",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Skoda",
    "model": "Enyaq Coupé",
    "variant": "85 Sportline 286 hk",
    "udbetaling_kr": 19995,
    "ydelse_kr": 5195,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/enyaq/ny-enyaq-coupe",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Skoda",
    "model": "Enyaq Coupé",
    "variant": "85 Sportline 286 hk",
    "udbetaling_kr": 39995,
    "ydelse_kr": 4495,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/enyaq/ny-enyaq-coupe",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Skoda",
    "model": "Enyaq Coupé",
    "variant": "RS 4x4 340 hk",
    "udbetaling_kr": 39995,
    "ydelse_kr": 5195,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/enyaq/ny-enyaq-coupe",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Skoda",
    "model": "Peaq",
    "variant": "60 Selection 204 hk",
    "udbetaling_kr": 29995,
    "ydelse_kr": 4595,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/peaq/peaq",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Skoda",
    "model": "Peaq",
    "variant": "90 Selection 286 hk",
    "udbetaling_kr": 29995,
    "ydelse_kr": 5395,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/peaq/peaq",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Skoda",
    "model": "Peaq",
    "variant": "90 Sportline 286 hk",
    "udbetaling_kr": 29995,
    "ydelse_kr": 6195,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/peaq/peaq",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Skoda",
    "model": "Peaq",
    "variant": "60 Selection 204 hk",
    "udbetaling_kr": 59995,
    "ydelse_kr": 3495,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/peaq/peaq",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Skoda",
    "model": "Peaq",
    "variant": "90 Selection 286 hk",
    "udbetaling_kr": 59995,
    "ydelse_kr": 4295,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/peaq/peaq",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Skoda",
    "model": "Peaq",
    "variant": "90 Sportline 286 hk",
    "udbetaling_kr": 59995,
    "ydelse_kr": 5095,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/peaq/peaq",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Skoda",
    "model": "Peaq",
    "variant": "90x Selection 299 hk",
    "udbetaling_kr": 29995,
    "ydelse_kr": 5995,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/peaq/peaq",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Skoda",
    "model": "Peaq",
    "variant": "90x Selection 299 hk",
    "udbetaling_kr": 59995,
    "ydelse_kr": 4895,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/peaq/peaq",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Skoda",
    "model": "Peaq",
    "variant": "90x Sportline 299 hk",
    "udbetaling_kr": 29995,
    "ydelse_kr": 6795,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/peaq/peaq",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Skoda",
    "model": "Peaq",
    "variant": "90x Sportline 299 hk",
    "udbetaling_kr": 59995,
    "ydelse_kr": 5695,
    "loebetid_mdr": 48,
    "km_aar": 10000,
    "kilde_url": "https://www.skoda.dk/modeller/peaq/peaq",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "BMW",
    "model": "iX1",
    "variant": "eDrive20 M Sport",
    "udbetaling_kr": 20000,
    "ydelse_kr": 3995,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#ix1",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "BMW",
    "model": "iX1",
    "variant": "eDrive20 Fully Charged",
    "udbetaling_kr": 20000,
    "ydelse_kr": 4295,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#ix1",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "BMW",
    "model": "iX1",
    "variant": "eDrive20 Supercharged",
    "udbetaling_kr": 20000,
    "ydelse_kr": 4595,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#ix1",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "BMW",
    "model": "iX1",
    "variant": "xDrive30 M Sport",
    "udbetaling_kr": 20000,
    "ydelse_kr": 4395,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#ix1",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "BMW",
    "model": "iX1",
    "variant": "xDrive30 Fully Charged",
    "udbetaling_kr": 20000,
    "ydelse_kr": 4695,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#ix1",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "BMW",
    "model": "iX1",
    "variant": "xDrive30 Supercharged",
    "udbetaling_kr": 20000,
    "ydelse_kr": 4995,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#ix1",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "BMW",
    "model": "iX2",
    "variant": "eDrive20 M Sport",
    "udbetaling_kr": 20000,
    "ydelse_kr": 4195,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#ix2",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "BMW",
    "model": "iX2",
    "variant": "eDrive20 Fully Charged",
    "udbetaling_kr": 20000,
    "ydelse_kr": 4495,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#ix2",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "BMW",
    "model": "iX2",
    "variant": "eDrive20 Supercharged",
    "udbetaling_kr": 20000,
    "ydelse_kr": 4795,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#ix2",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "BMW",
    "model": "iX2",
    "variant": "xDrive30 M Sport",
    "udbetaling_kr": 20000,
    "ydelse_kr": 4595,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#ix2",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "BMW",
    "model": "iX2",
    "variant": "xDrive30 Fully Charged",
    "udbetaling_kr": 20000,
    "ydelse_kr": 4895,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#ix2",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "BMW",
    "model": "iX2",
    "variant": "xDrive30 Supercharged",
    "udbetaling_kr": 20000,
    "ydelse_kr": 5195,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#ix2",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "BMW",
    "model": "iX3",
    "variant": "40 Active editon",
    "udbetaling_kr": 35000,
    "ydelse_kr": 5495,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#ix3",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "BMW",
    "model": "iX3",
    "variant": "40 M Sport",
    "udbetaling_kr": 35000,
    "ydelse_kr": 5795,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#ix3",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "BMW",
    "model": "iX3",
    "variant": "40 Fully Charged",
    "udbetaling_kr": 35000,
    "ydelse_kr": 6295,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#ix3",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "BMW",
    "model": "iX3",
    "variant": "40 Supercharged",
    "udbetaling_kr": 35000,
    "ydelse_kr": 6495,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#ix3",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "BMW",
    "model": "iX3",
    "variant": "40 Super Charged M Sport Pro",
    "udbetaling_kr": 35000,
    "ydelse_kr": 6695,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#ix3",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "BMW",
    "model": "iX3",
    "variant": "xDrive50",
    "udbetaling_kr": 35000,
    "ydelse_kr": 6495,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#ix3",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "BMW",
    "model": "iX3",
    "variant": "xDrive50 M Sport",
    "udbetaling_kr": 35000,
    "ydelse_kr": 6795,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#ix3",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "BMW",
    "model": "iX3",
    "variant": "xDrive50 Fully Charged",
    "udbetaling_kr": 35000,
    "ydelse_kr": 7295,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#ix3",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "BMW",
    "model": "iX3",
    "variant": "xDrive50 Supercharged",
    "udbetaling_kr": 35000,
    "ydelse_kr": 7495,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#ix3",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "BMW",
    "model": "i3",
    "variant": "xDrive50 First edition (12 mdr.)",
    "udbetaling_kr": 15000,
    "ydelse_kr": 6495,
    "loebetid_mdr": 12,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#i3",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "BMW",
    "model": "i3",
    "variant": "xDrive50 First edition (48 mdr.)",
    "udbetaling_kr": 35000,
    "ydelse_kr": 6495,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#i3",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "BMW",
    "model": "i4",
    "variant": "eDrive35 M Sport",
    "udbetaling_kr": 25000,
    "ydelse_kr": 5195,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#i4",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "BMW",
    "model": "i4",
    "variant": "eDrive35 Fully Charged",
    "udbetaling_kr": 25000,
    "ydelse_kr": 5695,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#i4",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "BMW",
    "model": "i4",
    "variant": "M60 xDrive",
    "udbetaling_kr": 35000,
    "ydelse_kr": 5895,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#i4",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "BMW",
    "model": "i4",
    "variant": "M60 xDrive Fully Charged",
    "udbetaling_kr": 35000,
    "ydelse_kr": 6195,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#i4",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "BMW",
    "model": "i5 Touring",
    "variant": "eDrive40 Touring M Sport",
    "udbetaling_kr": 30000,
    "ydelse_kr": 5995,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#i5-touring",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "BMW",
    "model": "i5 Touring",
    "variant": "eDrive40 Touring Fully Charged",
    "udbetaling_kr": 30000,
    "ydelse_kr": 6595,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#i5-touring",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "BMW",
    "model": "i5 Touring",
    "variant": "eDrive40 Touring Supercharged",
    "udbetaling_kr": 30000,
    "ydelse_kr": 7195,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#i5-touring",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "BMW",
    "model": "i5 Sedan",
    "variant": "eDrive40 Sedan M Sport",
    "udbetaling_kr": 30000,
    "ydelse_kr": 5995,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#i5-sedan",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "BMW",
    "model": "i5 Sedan",
    "variant": "eDrive40 Sedan Fully Charged",
    "udbetaling_kr": 30000,
    "ydelse_kr": 6595,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#i5-sedan",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "BMW",
    "model": "i5 Sedan",
    "variant": "eDrive40 Sedan Supercharged",
    "udbetaling_kr": 30000,
    "ydelse_kr": 7195,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#i5-sedan",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "BMW",
    "model": "iX",
    "variant": "xDrive60 M Sport",
    "udbetaling_kr": 50000,
    "ydelse_kr": 8995,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#ix",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "BMW",
    "model": "iX",
    "variant": "xDrive60 Fully Charged",
    "udbetaling_kr": 50000,
    "ydelse_kr": 9495,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#ix",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "BMW",
    "model": "iX",
    "variant": "xDrive60 Super Charged",
    "udbetaling_kr": 50000,
    "ydelse_kr": 9995,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#ix",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "BMW",
    "model": "i7",
    "variant": "xDrive50 M Sport",
    "udbetaling_kr": 50000,
    "ydelse_kr": 10995,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#i7",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "BMW",
    "model": "i7",
    "variant": "xDrive50 Fully Charged",
    "udbetaling_kr": 50000,
    "ydelse_kr": 12995,
    "loebetid_mdr": 48,
    "km_aar": 15000,
    "kilde_url": "https://www.bmw.dk/da/bmw-financial-services-oversikt/tilbud/privatleasing-og-lan.html#i7",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Hyundai",
    "model": "INSTER",
    "variant": "42 kWh, 97 hk, Essential",
    "udbetaling_kr": 29995,
    "ydelse_kr": 2295,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.hyundai.dk/privatleasing/inster-privatleasing",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Hyundai",
    "model": "INSTER",
    "variant": "42 kWh, 97 hk, Essential",
    "udbetaling_kr": 4995,
    "ydelse_kr": 3195,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.hyundai.dk/privatleasing/inster-privatleasing",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Hyundai",
    "model": "KONA Electric",
    "variant": "48,4 kWh, 156 hk, Essential",
    "udbetaling_kr": 49995,
    "ydelse_kr": 2495,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.hyundai.dk/privatleasing/kona-privatleasing",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Hyundai",
    "model": "KONA Electric",
    "variant": "48,4 kWh, 156 hk, Essential",
    "udbetaling_kr": 14995,
    "ydelse_kr": 3695,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.hyundai.dk/privatleasing/kona-privatleasing",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Hyundai",
    "model": "IONIQ 5",
    "variant": "63 kWh 170 hk RWD Essential Standard Range",
    "udbetaling_kr": 49995,
    "ydelse_kr": 2895,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.hyundai.dk/privatleasing/ioniq-5-privatleasing",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Hyundai",
    "model": "IONIQ 5",
    "variant": "63 kWh 170 hk RWD Essential Standard Range",
    "udbetaling_kr": 14995,
    "ydelse_kr": 4095,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.hyundai.dk/privatleasing/ioniq-5-privatleasing",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Hyundai",
    "model": "IONIQ 5 N",
    "variant": "84 kWh 650 hk",
    "udbetaling_kr": 49995,
    "ydelse_kr": 6595,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.hyundai.dk/privatleasing/ioniq-5-privatleasing#ioniq-5-n",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Hyundai",
    "model": "IONIQ 5 N",
    "variant": "84 kWh 650 hk",
    "udbetaling_kr": 14995,
    "ydelse_kr": 7895,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.hyundai.dk/privatleasing/ioniq-5-privatleasing#ioniq-5-n",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Hyundai",
    "model": "IONIQ 6",
    "variant": "63 kWh 170 hk RWD Essential Standard Range",
    "udbetaling_kr": 49995,
    "ydelse_kr": 3695,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.hyundai.dk/privatleasing/ioniq-6-privatleasing",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Hyundai",
    "model": "IONIQ 6",
    "variant": "63 kWh 170 hk RWD Essential Standard Range",
    "udbetaling_kr": 14995,
    "ydelse_kr": 4895,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.hyundai.dk/privatleasing/ioniq-6-privatleasing",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Hyundai",
    "model": "IONIQ 6 N",
    "variant": "84 kWh 609 hk",
    "udbetaling_kr": 49995,
    "ydelse_kr": 6595,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.hyundai.dk/privatleasing/ioniq-6-privatleasing#ioniq-6-n",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Hyundai",
    "model": "IONIQ 6 N",
    "variant": "84 kWh 609 hk",
    "udbetaling_kr": 14995,
    "ydelse_kr": 7895,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.hyundai.dk/privatleasing/ioniq-6-privatleasing#ioniq-6-n",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "hatchback"
  },
  {
    "maerke": "Hyundai",
    "model": "IONIQ 9",
    "variant": "110,3 kWh 218 hk RWD Advanced 7 sæder",
    "udbetaling_kr": 49995,
    "ydelse_kr": 6395,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.hyundai.dk/privatleasing/ioniq-9-privatleasing",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  },
  {
    "maerke": "Hyundai",
    "model": "IONIQ 9",
    "variant": "110,3 kWh 218 hk RWD Advanced 7 sæder",
    "udbetaling_kr": 14995,
    "ydelse_kr": 7595,
    "loebetid_mdr": 36,
    "km_aar": 10000,
    "kilde_url": "https://www.hyundai.dk/privatleasing/ioniq-9-privatleasing",
    "sidst_tjekket": "2026-08-22",
    "status": "Aktiv",
    "type": "suv"
  }
];
