// Auto-generated by build_model_pages.py -- do not hand-edit.
// Keyed by "Maerke|Model". Only brands with verified real spec data
// appear here -- see parse_vw_specs.py. Absence is intentional, not a bug.
const MODEL_SPECS = {
  "Volkswagen|T-Roc": {
    "type": "petrol",
    "co2_g_km": 128.0,
    "forbrug": "17.9 km/l",
    "ejerafgift_halvaar_kr": 760
  },
  "Volkswagen|ID. Buzz Kort": {
    "type": "electric",
    "raekkevidde_km_min": 417,
    "raekkevidde_km_max": 455,
    "forbrug": "19.4 kWh/100km"
  },
  "Volkswagen|ID. Buzz Lang": {
    "type": "electric",
    "raekkevidde_km_min": 454,
    "raekkevidde_km_max": 480,
    "forbrug": "20.2 kWh/100km"
  },
  "Volkswagen|ID. Polo": {
    "type": "electric",
    "raekkevidde_km_min": 442,
    "raekkevidde_km_max": 453,
    "forbrug": "13.3 kWh/100km"
  },
  "Volkswagen|ID.3 Neo": {
    "type": "electric",
    "raekkevidde_km_min": 414,
    "raekkevidde_km_max": 626,
    "forbrug": "14.1 kWh/100km"
  },
  "Volkswagen|ID.4": {
    "type": "electric",
    "raekkevidde_km_min": 519,
    "raekkevidde_km_max": 558,
    "forbrug": "15.8 kWh/100km"
  },
  "Volkswagen|ID.7 Tourer": {
    "type": "electric",
    "raekkevidde_km_min": 586,
    "raekkevidde_km_max": 677,
    "forbrug": "14.3 kWh/100km"
  },
  "Volkswagen|ID.5": {
    "type": "electric",
    "raekkevidde_km_min": 557,
    "raekkevidde_km_max": 563,
    "forbrug": "15.7 kWh/100km"
  }
};
